name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch deployment branch
      run: git fetch origin deployment:deployment

    - name: Attempt merge
      id: merge_attempt
      run: |
        git checkout deployment
        git merge origin/main --no-edit || echo "MERGE_FAILED=true" >> $GITHUB_ENV

    - name: Push to deployment branch
      if: env.MERGE_FAILED != 'true'
      run: |
        git push origin deployment

    - name: Deploy to Fly.io
      if: env.MERGE_FAILED != 'true'
      uses: superfly/flyctl-actions@1.4
      with:
        args: deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
